### ISSUE TITLE
paganini-theme is not available in MELPA

### ISSUE THREAD

**Issue by ciukstar** [onurtemizkan/paganini#1]
After last update, my paganini-theme "disappeared" and it is not available in MELPA

**Comment by onurtemizkan** [comment]
@ciukstar, thanks for reporting. It seems that MELPA hadn't fetched the last update somehow. And because of that, the MELPA recipe had been mismatched with the repository. It should be there now.

**Comment by ciukstar** [comment]
Nope, no paganini-theme on MELPA.

`Install package: paganini-theme [No match]`

**Comment by onurtemizkan** [comment]
Looks like I've removed an `autoload` magic comment in the last update. Reverted it. Please update your MELPA packages list and try to install `paganini-theme`. You may close the issue if it's resolved. Thanks.

**Comment by ciukstar** [comment]
Successfully installed from MELPA. Thanks!
